### ISSUE TITLE
PumasPlots currently broken on v1.1 Pumas

### ISSUE THREAD

**Issue by vjd** [PumasAI/PumasPlots.jl#11]
due to https://github.com/PumasAI/PumasPlots.jl/blob/543fba0165e70f87ec3f2ac0f24cbf357a1112be/src/utils.jl#L52

`NoCovar` has been removed from Pumas, and we do the check differently.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/PumasAI/PumasPlots.jl/pull/12
